/** 精选入口。分类 ID 固定，站点只在对应版本首次升级时补入。 */
export const CURATED_QUICK_GROUPS = [
  { id: 'featured-ai', name: 'AI 助手', sites: [
    { name: 'ChatGPT', url: 'https://chatgpt.com/' },
    { name: 'Claude', url: 'https://claude.ai/' },
    { name: 'Perplexity', url: 'https://www.perplexity.ai/' },
    { name: 'DeepSeek', url: 'https://chat.deepseek.com/' },
    { name: 'Kimi', url: 'https://www.kimi.com/' },
    { name: '豆包', url: 'https://www.doubao.com/' },
    { name: 'Gemini', url: 'https://gemini.google.com/' },
    { name: '通义千问', url: 'https://chat.qwen.ai/' },
    { name: '腾讯元宝', url: 'https://yuanbao.tencent.com/' },
    { name: '智谱清言', url: 'https://chatglm.cn/' },
    { name: '文心助手', url: 'https://wenxin.baidu.com/' },
    { name: 'Microsoft Copilot', url: 'https://copilot.microsoft.com/' },
    { name: 'Grok', url: 'https://grok.com/' },
    { name: 'NotebookLM', url: 'https://notebooklm.google.com/' },
    { name: 'Poe', url: 'https://poe.com/' },
    { name: 'Mistral Le Chat', url: 'https://chat.mistral.ai/' },
    { name: '秘塔 AI 搜索', url: 'https://metaso.cn/' },
    { name: 'You.com', url: 'https://you.com/' },
    { name: 'Genspark', url: 'https://www.genspark.ai/' },
    { name: 'Manus', url: 'https://manus.im/' },
  ] },
  { id: 'featured-news', name: '精选资讯', sites: [
    { name: '少数派', url: 'https://sspai.com/' },
    { name: '36氪', url: 'https://36kr.com/' },
    { name: 'Hacker News', url: 'https://news.ycombinator.com/' },
    { name: '知乎', url: 'https://www.zhihu.com/' },
    { name: 'Product Hunt', url: 'https://www.producthunt.com/' },
    { name: '虎嗅', url: 'https://www.huxiu.com/' },
    { name: '钛媒体', url: 'https://www.tmtpost.com/' },
    { name: '极客公园', url: 'https://www.geekpark.net/' },
    { name: '爱范儿', url: 'https://www.ifanr.com/' },
    { name: '机器之心', url: 'https://www.jiqizhixin.com/' },
    { name: '量子位', url: 'https://www.qbitai.com/' },
    { name: 'The Verge', url: 'https://www.theverge.com/' },
    { name: 'Ars Technica', url: 'https://arstechnica.com/' },
    { name: 'TechCrunch', url: 'https://techcrunch.com/' },
    { name: 'WIRED', url: 'https://www.wired.com/' },
    { name: 'MIT Technology Review', url: 'https://www.technologyreview.com/' },
    { name: 'Reuters', url: 'https://www.reuters.com/' },
    { name: 'AP News', url: 'https://apnews.com/' },
    { name: 'Rest of World', url: 'https://restofworld.org/' },
    { name: 'The Conversation', url: 'https://theconversation.com/' },
  ] },
  { id: 'featured-learn', name: '学习成长', sites: [
    { name: 'Coursera', url: 'https://www.coursera.org/' },
    { name: '可汗学院', url: 'https://www.khanacademy.org/' },
    { name: '中国大学 MOOC', url: 'https://www.icourse163.org/' },
    { name: '学堂在线', url: 'https://www.xuetangx.com/' },
    { name: 'freeCodeCamp', url: 'https://www.freecodecamp.org/' },
    { name: 'edX', url: 'https://www.edx.org/' },
    { name: 'MIT OpenCourseWare', url: 'https://ocw.mit.edu/' },
    { name: 'Udemy', url: 'https://www.udemy.com/' },
    { name: 'Udacity', url: 'https://www.udacity.com/' },
    { name: 'Codecademy', url: 'https://www.codecademy.com/' },
    { name: 'Scrimba', url: 'https://scrimba.com/' },
    { name: 'The Odin Project', url: 'https://www.theodinproject.com/' },
    { name: 'MDN Web Docs', url: 'https://developer.mozilla.org/' },
    { name: '菜鸟教程', url: 'https://www.runoob.com/' },
    { name: '廖雪峰教程', url: 'https://liaoxuefeng.com/' },
    { name: '极客时间', url: 'https://time.geekbang.org/' },
    { name: '慕课网', url: 'https://www.imooc.com/' },
    { name: '国家智慧教育平台', url: 'https://www.smartedu.cn/' },
    { name: '智慧树', url: 'https://www.zhihuishu.com/' },
    { name: '哔哩哔哩', url: 'https://www.bilibili.com/' },
  ] },
  { id: 'featured-design', name: '设计创作', sites: [
    { name: 'Figma', url: 'https://www.figma.com/' },
    { name: 'Canva 可画', url: 'https://www.canva.cn/' },
    { name: '即时设计', url: 'https://js.design/' },
    { name: 'MasterGo', url: 'https://mastergo.com/' },
    { name: 'Adobe Express', url: 'https://www.adobe.com/express/' },
    { name: 'Framer', url: 'https://www.framer.com/' },
    { name: 'Webflow', url: 'https://webflow.com/' },
    { name: 'Penpot', url: 'https://penpot.app/' },
    { name: 'Sketch', url: 'https://www.sketch.com/' },
    { name: 'Behance', url: 'https://www.behance.net/' },
    { name: 'Dribbble', url: 'https://dribbble.com/' },
    { name: 'Awwwards', url: 'https://www.awwwards.com/' },
    { name: 'Mobbin', url: 'https://mobbin.com/' },
    { name: 'Adobe Color', url: 'https://color.adobe.com/' },
    { name: 'Coolors', url: 'https://coolors.co/' },
    { name: '站酷', url: 'https://www.zcool.com.cn/' },
    { name: '花瓣', url: 'https://huaban.com/' },
    { name: 'UI 中国', url: 'https://www.ui.cn/' },
    { name: 'Unsplash', url: 'https://unsplash.com/' },
    { name: 'Iconfont', url: 'https://www.iconfont.cn/' },
  ] },
] as const;

export const CURATED_QUICK_GROUP_IDS = new Set<string>(CURATED_QUICK_GROUPS.map((group) => group.id));

/** 第一版曾提供的三个分类；升级后其站点回到默认快捷访问。 */
export const RETIRED_CURATED_QUICK_GROUP_IDS = new Set(['featured-dev', 'featured-work', 'featured-assets']);

/** 升级第一版用户时，保留他们对旧精选站点的删除选择。 */
export const FIRST_CURATED_SITE_URLS: Record<string, ReadonlySet<string>> = {
  'featured-ai': new Set([
    'https://chatgpt.com/', 'https://claude.ai/', 'https://www.perplexity.ai/',
    'https://chat.deepseek.com/', 'https://www.kimi.com/', 'https://www.doubao.com/',
  ]),
  'featured-news': new Set([
    'https://sspai.com/', 'https://36kr.com/', 'https://news.ycombinator.com/',
    'https://www.zhihu.com/', 'https://www.producthunt.com/',
  ]),
  'featured-learn': new Set([
    'https://www.coursera.org/', 'https://www.khanacademy.org/', 'https://www.icourse163.org/',
    'https://www.xuetangx.com/', 'https://www.freecodecamp.org/',
  ]),
  'featured-design': new Set([
    'https://www.figma.com/', 'https://www.canva.cn/', 'https://js.design/',
    'https://mastergo.com/', 'https://www.adobe.com/express/',
  ]),
};
